#!/usr/bin/env bash
# Install the benchmark and prepare pretrained models.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV="$ROOT/.venv"
MODELS="$ROOT/pretrained"
DEVICE=cuda:0
DOWNLOAD=1
PYTHON="${PYTHON_BIN:-python3.11}"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --venv) VENV="$2"; shift 2 ;;
    --models-dir) MODELS="$2"; shift 2 ;;
    --device) DEVICE="$2"; shift 2 ;;
    --skip-models) DOWNLOAD=0; shift ;;
    -h|--help)
      echo "Usage: bash scripts/setup.sh [--venv DIR] [--models-dir DIR] [--device cuda:N] [--skip-models]"
      exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 2 ;;
  esac
done
command -v "$PYTHON" >/dev/null || { echo 'Python 3.11 is required. Set PYTHON_BIN to its executable.' >&2; exit 1; }
"$PYTHON" -c 'import sys; assert sys.version_info[:2] == (3, 11), "Use Python 3.11"'
command -v git >/dev/null || { echo 'Install git before running setup.' >&2; exit 1; }
VENV="$(realpath -m "$VENV")"
MODELS="$(realpath -m "$MODELS")"
if [[ ! -x "$VENV/bin/python" ]]; then "$PYTHON" -m venv "$VENV"; fi
"$VENV/bin/python" -c 'import sys; assert sys.version_info[:2] == (3, 11), "The existing environment must use Python 3.11"'
cd "$ROOT"
"$VENV/bin/python" -m pip install -r requirements.txt
"$VENV/bin/python" -m pip check
"$VENV/bin/python" scripts/check_environment.py --device "$DEVICE"
if [[ "$DOWNLOAD" == 1 ]]; then
  "$VENV/bin/python" scripts/prepare_models.py --output "$MODELS"
fi
{
  printf '# Generated by scripts/setup.sh\n'
  printf 'source %q\n' "$VENV/bin/activate"
  if [[ "$DOWNLOAD" == 1 ]]; then printf 'source %q\n' "$MODELS/env.sh"; fi
} > .iesseeg-env.sh
printf '\nSetup complete. Run: source %q\n' "$ROOT/.iesseeg-env.sh"
